name: Develop

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - dev
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      IMAGE_URL: ${{ vars.ACR_NAME }}.azurecr.io/${{ vars.CONTAINER_IMAGE_NAME }}
    steps:
      - uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CI }}

      - name: Login ACR
        run: az acr login --name ${{ vars.ACR_NAME }}

      - name: Config
        run: |
          APIM_VERSION=$(cat APIM_VERSION)
          VERSION=$(echo $APIM_VERSION | sed -e 's/^v//')
          VERSION="${VERSION}-${{ github.run_number }}"
          echo "VERSION=$(echo $VERSION)" >> $GITHUB_ENV
          echo "APIM_VERSION=$(echo $APIM_VERSION)" >> $GITHUB_ENV

      - name: Build image
        run: |
          docker build --platform linux/amd64 \
            --build-arg APIM_VERSION=${{ env.APIM_VERSION }} \
            -t ${{ env.IMAGE_URL }}:${{ env.VERSION }} .

      - name: Publish image
        run: docker push ${{ env.IMAGE_URL }}:${{ env.VERSION }}
